// The site's sections (ADR 0008): every article belongs to one, chosen by its infobox kind.
// The table is data: move a kind by editing it. A kind not listed goes to `other`.

export const SECTIONS = [
  'characters',
  'species',
  'planets',
  'places',
  'galaxy',
  'starships',
  'vehicles',
  'organizations',
  'events',
  'technology',
  'lore',
  'media',
  'real-world',
  'other',
] as const;

export type Section = (typeof SECTIONS)[number];

/** Infobox kinds per section, written without underscores (`Starship_class` is `StarshipClass`). */
const KINDS: Readonly<Record<Exclude<Section, 'other'>, readonly string[]>> = {
  characters: ['Character', 'Droid', 'Family', 'Deity'],
  species: ['Species', 'CulturalGroup'],
  planets: ['CelestialBody', 'Star', 'StarType'],
  places: ['Location', 'City', 'Structure', 'Store', 'RacingTrack', 'TerrestrialLocation'],
  galaxy: [
    'System',
    'Sector',
    'Region',
    'Nebula',
    'StarCluster',
    'TradeRoute',
    'Galaxy',
    'GalacticLocation',
    'Constellation',
    'Hyperspace',
  ],
  starships: [
    'StarshipClass',
    'IndividualShip',
    'ShipSeries',
    'SpaceStation',
    'SpaceStationClass',
    'Fleet',
  ],
  vehicles: [
    'RepulsorliftVehicle',
    'GroundVehicle',
    'AirVehicle',
    'AquaticVehicle',
    'IndividualVehicle',
    'Vehicle',
  ],
  organizations: ['Organization', 'MilitaryUnit', 'Company', 'Government', 'Religion'],
  events: [
    'Battle',
    'War',
    'Campaign',
    'Mission',
    'Duel',
    'Event',
    'Election',
    'Treaty',
    'Holiday',
    'Competition',
  ],
  technology: [
    'Device',
    'Weapon',
    'Armor',
    'Lightsaber',
    'Artifact',
    'DroidSeries',
    'Clothing',
    'Medal',
    'Currency',
    'HolocronInfobox',
  ],
  lore: [
    'ForcePower',
    'LightsaberForm',
    'Language',
    'TitleOrPosition',
    'Year',
    'Month',
    'Era',
    'Food',
    'Plant',
    'Substance',
    'Disease',
    'Tactics',
    'Law',
    'Sport',
    'Symbol',
    'Aurebesh',
    'CanonAurebesh',
  ],
  media: [
    'Movie',
    'TelevisionSeries',
    'TelevisionSeason',
    'TelevisionEpisode',
    'Book',
    'BookSeries',
    'BookCollection',
    'ShortStory',
    'ReferenceBook',
    'Audiobook',
    'AudiobookSeries',
    'ComicBook',
    'ComicStory',
    'ComicCollection',
    'ComicSeries',
    'ComicArc',
    'ComicMagazine',
    'ComicStrip',
    'GraphicNovel',
    'Webstrip',
    'VideoGame',
    'VideoGameSeries',
    'Game',
    'BoardGame',
    'TabletopGame',
    'Adventure',
    'ExpansionPack',
    'ActivityBook',
    'MagazineArticle',
    'MagazineIssue',
    'MagazineSeries',
    'MagazineDepartment',
    'ReferenceMagazine',
    'Magazine',
    'InUniverseMedia',
    'IUMedia',
    'Documentary',
    'Script',
    'Soundtrack',
    'Music',
    'HomeVideo',
    'LiveShow',
    'WebArticle',
    'Media',
    'Multimedia',
    'App',
  ],
  'real-world': [
    'Person',
    'RealCompany',
    'Band',
    'ToyLine',
    'TradingCardSet',
    'Website',
    'FanPodcast',
    'FanOrganization',
    'RealEvent',
    'OOUEvent',
    'FilmingLocation',
  ],
};

const bySpelling = new Map<string, Section>(
  Object.entries(KINDS).flatMap(([section, kinds]) =>
    kinds.map((k) => [k.toLowerCase(), section as Section] as const),
  ),
);

/** `Starship_class`, `starshipclass` and `StarshipClass` are one kind. */
export const normaliseKind = (kind: string): string => kind.replace(/[_\s]/g, '').toLowerCase();

export const sectionOf = (kind: string | undefined): Section =>
  kind === undefined ? 'other' : (bySpelling.get(normaliseKind(kind)) ?? 'other');
