// Generated by `pnpm caddyfile`. Don't edit by hand.
// The CSP allows these inline elements by hash, so neither style-src nor script-src needs
// 'unsafe-inline' (src/hosting/headers.ts).

/** Each island's declarative shadow root <style>. */
export const STYLE_HASHES: readonly string[] = [
  "'sha256-g7QtR2SARqkTM/cUF4nkFfkXuXKRsnKL6Qk94bISuvA='",
];

/** The theme script in every page's <head> (src/domain/theme.ts). */
export const SCRIPT_HASHES: readonly string[] = [
  "'sha256-Cg25GLqXp6/RN8mqJrk4Ce85qdFMkXsDai8d3gOtkFc='",
];
