// The response headers policy (docs/design-docs/0003-hosting.md), in one place:
// - scripts/preview.ts applies headersFor(), so `pnpm smoke` runs the site under the real CSP;
// - caddyfile() renders the same policy for production; `pnpm caddyfile` writes it to
//   Caddyfile, and a test fails if the committed file drifts from this code.
import { SCRIPT_HASHES, STYLE_HASHES } from './csp-hashes.js';

/**
 * - style-src: the stylesheet, and each island's Declarative Shadow DOM <style> by its hash
 *   (STYLE_HASHES, generated by `pnpm caddyfile`). No 'unsafe-inline': nothing else may style.
 * - script-src: the site's own files, and the theme script in each page's head by its hash
 *   (SCRIPT_HASHES); no other inline script, no eval(), no WebAssembly (search runs on the
 *   server since ADR 0011).
 */
export const CSP = [
  "default-src 'self'",
  `script-src 'self' ${SCRIPT_HASHES.join(' ')}`,
  `style-src 'self' ${STYLE_HASHES.join(' ')}`,
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self'",
  "base-uri 'none'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  "object-src 'none'",
  'upgrade-insecure-requests',
].join('; ');

/** On every response. */
export const SECURITY: Readonly<Record<string, string>> = {
  'Content-Security-Policy': CSP,
  // No includeSubDomains: other starwars.run subdomains aren't this site's to promise.
  'Strict-Transport-Security': 'max-age=63072000',
  'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=(), usb=()',
  'Cross-Origin-Opener-Policy': 'same-origin',
};

/**
 * Hover-to-fetch (ADR 0011): every page points browsers at one rules file, which asks them to
 * fetch a page while its link is hovered, so the click lands on a page already there. A header,
 * not an inline <script type="speculationrules">, so the CSP needs no exception. Browsers only
 * read the rules if the file has its own MIME type.
 */
export const SPECULATION_RULES = {
  path: '/speculation-rules.json',
  type: 'application/speculationrules+json',
} as const;

/** On every response, beside the security headers. */
export const NAVIGATION: Readonly<Record<string, string>> = {
  'Speculation-Rules': `"${SPECULATION_RULES.path}"`,
};

/**
 * Cache-Control by path. Browsers revalidate pages after 5 minutes; Cloudflare keeps them a week
 * (s-maxage), until a deploy purges it, and serves a stale copy while it refetches.
 */
export const CACHE = {
  /** Content-hashed file names: a new build means a new URL. */
  assets: 'public, max-age=31536000, immutable',
  /** Icons rarely change and aren't hashed. */
  icons: 'public, max-age=86400',
  /** The service worker must be rechecked on every load, or a deploy never reaches visitors. */
  serviceWorker: 'no-cache',
  /**
   * Pages, search results, the manifest and sitemaps. Content changes with new data or code,
   * which purges Cloudflare's cache (ADR 0011): Cloudflare may keep them a week, and serve a
   * stale copy while it refetches or while the app is down.
   */
  pages:
    'public, max-age=300, s-maxage=604800, stale-while-revalidate=86400, stale-if-error=604800',
  /** The 404 page: short, so a page that appears after a deploy isn't hidden for long. */
  notFound: 'public, max-age=60',
  /** Ask's answers and SQL results (/api/): each one is for one visitor, once. Search and
   * article previews change only with a build and are cached like pages. */
  api: 'no-store',
} as const;

/** Paths whose file names are content hashes: Vite's output. */
export const HASHED_PATHS = ['/assets/'] as const;

/** Search's endpoint and the public API paths (src/server/api.ts). */
export const CACHED_API = '/api/search';
export const CACHED_APIS = [CACHED_API, '/api/preview'] as const;

export function cacheControl(path: string, status: number): string {
  if (CACHED_APIS.some((p) => p === path)) return status === 404 ? CACHE.notFound : CACHE.pages;
  if (path.startsWith('/api/')) return CACHE.api;
  if (status === 404) return CACHE.notFound;
  if (HASHED_PATHS.some((p) => path.startsWith(p))) return CACHE.assets;
  if (path.startsWith('/icons/')) return CACHE.icons;
  if (path === '/sw.js') return CACHE.serviceWorker;
  return CACHE.pages;
}

/** Every header for a response to `path`. */
export const headersFor = (path: string, status: number): Readonly<Record<string, string>> => ({
  ...SECURITY,
  ...NAVIGATION,
  'Cache-Control': cacheControl(path, status),
});

const quote = (value: string): string => `"${value.replaceAll('"', '\\"')}"`;

/**
 * The production server config: Caddy on port 8080, serving the files in dist/ (copied to /srv)
 * and forwarding everything else, pages and /api/, to the app (ADR 0011).
 */
export function caddyfile(): string {
  // Caddy's error route doesn't run the main route's header directives, so the 404 page gets
  // its own copy of the security block.
  const security = (indent: string) =>
    [
      `${indent}header {`,
      ...Object.entries({ ...SECURITY, ...NAVIGATION }).map(
        ([name, value]) => `${indent}\t${name} ${quote(value)}`,
      ),
      `${indent}\t-Server`,
      `${indent}}`,
    ].join('\n');
  return `# Generated by \`pnpm caddyfile\` from src/hosting/headers.ts. Don't edit by hand.
{
\tadmin off
\tauto_https off
}

:8080 {
\troot * /srv
\tencode zstd gzip

${security('\t')}

\t@assets path ${HASHED_PATHS.map((p) => `${p}*`).join(' ')}
\theader @assets Cache-Control ${quote(CACHE.assets)}
\t@icons path /icons/*
\theader @icons Cache-Control ${quote(CACHE.icons)}
\t@sw path /sw.js
\theader @sw Cache-Control ${quote(CACHE.serviceWorker)}
\t@pages not path ${HASHED_PATHS.map((p) => `${p}*`).join(' ')} /icons/* /sw.js /api/*
\t# A default (?): the app sets its own on pages and 404s; this covers the static files.
\theader @pages ?Cache-Control ${quote(CACHE.pages)}
\t# Deferred (>), so it replaces the type Caddy guesses from .json.
\theader ${SPECULATION_RULES.path} >Content-Type ${quote(SPECULATION_RULES.type)}
\t# Deferred (>): the API sends its own Cache-Control, and this replaces it rather than adding a
\t# second. Search and article previews are cached like pages, as the app says.
\t@private {
\t\tpath /api/*
\t\tnot path ${CACHED_APIS.join(' ')}
\t}
\theader @private >Cache-Control ${quote(CACHE.api)}

\t# A file in /srv is served from disk: assets, icons, the manifest and service worker.
\t# Everything else goes to the app container, at API (ADRs 0010, 0011): every
\t# page, rendered on request, and /api/, whose Ask answers stream as server-sent events, so
\t# nothing is buffered. Unset, it goes nowhere.
\t@static {
\t\tfile
\t\tnot path */
\t}
\thandle @static {
\t\tfile_server
\t}
\thandle {
\t\trequest_body {
\t\t\tmax_size 64KB
\t\t}
\t\treverse_proxy {$API:http://127.0.0.1:9} {
\t\t\tflush_interval -1
\t\t}
\t}

\thandle_errors {
\t\trewrite * /404.html
${security('\t\t')}
\t\theader Cache-Control ${quote(CACHE.notFound)}
\t\tfile_server
\t}
}
`;
}
