// The response headers policy (docs/design-docs/0003-hosting.md), in one place:
// - scripts/preview.ts applies headersFor(), so `pnpm smoke` runs the site under the real CSP;
// - caddyfile() renders the same policy for production; `pnpm caddyfile` writes it to
//   Caddyfile, and a test fails if the committed file drifts from this code.

/**
 * - style-src 'unsafe-inline': Declarative Shadow DOM styles are inline <style> elements.
 * - script-src 'wasm-unsafe-eval': the search index (Pagefind) compiles WebAssembly. It does not
 *   allow eval() or inline scripts.
 */
export const CSP = [
  "default-src 'self'",
  "script-src 'self' 'wasm-unsafe-eval'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self'",
  "base-uri 'none'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  "object-src 'none'",
  'upgrade-insecure-requests',
].join('; ');

/** On every response. */
export const SECURITY: Readonly<Record<string, string>> = {
  'Content-Security-Policy': CSP,
  // No includeSubDomains: other starwars.run subdomains aren't this site's to promise.
  'Strict-Transport-Security': 'max-age=63072000',
  'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=(), usb=()',
  'Cross-Origin-Opener-Policy': 'same-origin',
};

/**
 * Cache-Control by path. Browsers revalidate pages after 5 minutes; Cloudflare keeps them an
 * hour (s-maxage) and serves a stale copy for up to a day while it refetches.
 */
export const CACHE = {
  /** Content-hashed file names: a new build means a new URL. */
  assets: 'public, max-age=31536000, immutable',
  /** Icons rarely change and aren't hashed. */
  icons: 'public, max-age=86400',
  /** The service worker must be rechecked on every load, or a deploy never reaches visitors. */
  serviceWorker: 'no-cache',
  /** HTML, Pagefind's entry files, the manifest, the sitemaps. */
  pages: 'public, max-age=300, s-maxage=3600, stale-while-revalidate=86400',
  /** The 404 page: short, so a page that appears after a deploy isn't hidden for long. */
  notFound: 'public, max-age=60',
} as const;

/** Paths whose file names are content hashes: Vite's output and Pagefind's index parts. */
export const HASHED_PATHS = [
  '/assets/',
  '/pagefind/index/',
  '/pagefind/fragment/',
  '/pagefind/filter/',
] as const;

export function cacheControl(path: string, status: number): string {
  if (status === 404) return CACHE.notFound;
  if (HASHED_PATHS.some((p) => path.startsWith(p))) return CACHE.assets;
  if (path.startsWith('/icons/')) return CACHE.icons;
  if (path === '/sw.js') return CACHE.serviceWorker;
  return CACHE.pages;
}

/** Every header for a response to `path`. */
export const headersFor = (path: string, status: number): Readonly<Record<string, string>> => ({
  ...SECURITY,
  'Cache-Control': cacheControl(path, status),
});

const quote = (value: string): string => `"${value.replaceAll('"', '\\"')}"`;

/** The production server config: Caddy serving dist/ (copied to /srv) on port 8080. */
export function caddyfile(): string {
  // Caddy's error route doesn't run the main route's header directives, so the 404 page gets
  // its own copy of the security block.
  const security = (indent: string) =>
    [
      `${indent}header {`,
      ...Object.entries(SECURITY).map(([name, value]) => `${indent}\t${name} ${quote(value)}`),
      `${indent}\t-Server`,
      `${indent}}`,
    ].join('\n');
  return `# Generated by \`pnpm caddyfile\` from src/hosting/headers.ts. Don't edit by hand.
{
\tadmin off
\tauto_https off
}

:8080 {
\troot * /srv
\tencode zstd gzip

${security('\t')}

\t@assets path ${HASHED_PATHS.map((p) => `${p}*`).join(' ')}
\theader @assets Cache-Control ${quote(CACHE.assets)}
\t@icons path /icons/*
\theader @icons Cache-Control ${quote(CACHE.icons)}
\t@sw path /sw.js
\theader @sw Cache-Control ${quote(CACHE.serviceWorker)}
\t@pages not path ${HASHED_PATHS.map((p) => `${p}*`).join(' ')} /icons/* /sw.js
\theader @pages Cache-Control ${quote(CACHE.pages)}

\tfile_server

\thandle_errors {
\t\trewrite * /404.html
${security('\t\t')}
\t\theader Cache-Control ${quote(CACHE.notFound)}
\t\tfile_server
\t}
}
`;
}
