/// <reference types="node" />
// `pnpm caddyfile`: writes the islands' style hashes to src/hosting/style-hashes.ts, then the
// Caddyfile from src/hosting/headers.ts. Run it after changing the header policy or an island's
// styles, and commit both; test/hosting/headers.test.ts fails until you do.
import { writeFile } from 'node:fs/promises';
import { styleHashes } from '@gyral/core/server';

// Registering the islands is what makes their styles known.
await import('../src/islands/site-search.js');
await import('../src/islands/explore.js');
// Sorted: the order islands register in is no part of the policy.
const hashes = [...(await styleHashes())].sort();
await writeFile(
  new URL('../src/hosting/style-hashes.ts', import.meta.url),
  `// Generated by \`pnpm caddyfile\` from the islands' styles. Don't edit by hand.
// The CSP allows these <style> elements (each island's declarative shadow root) by hash, so
// style-src needs no 'unsafe-inline' (src/hosting/headers.ts).
export const STYLE_HASHES: readonly string[] = [
${hashes.map((h) => `  ${JSON.stringify(h)},`).join('\n')}
];
`,
);
// headers.ts reads the hashes, so it's imported after they're written.
const { caddyfile } = await import('../src/hosting/headers.js');
await writeFile(new URL('../Caddyfile', import.meta.url), caddyfile());
console.log(`wrote src/hosting/style-hashes.ts (${String(hashes.length)} hashes) and Caddyfile`);
