/// <reference types="node" />
// `pnpm caddyfile`: writes the CSP's hashes to src/hosting/csp-hashes.ts (the islands' styles,
// and the theme script every page inlines), then the Caddyfile from src/hosting/headers.ts. Run
// it after changing the header policy, an island's styles or the theme script, and commit both;
// test/hosting/headers.test.ts fails until you do.
import { createHash } from 'node:crypto';
import { writeFile } from 'node:fs/promises';
import { styleHashes } from '@gyral/core/server';
import { THEME_SCRIPT } from '../src/domain/theme.js';

// Registering the islands is what makes their styles known.
await import('../src/islands/site-search.js');
await import('../src/islands/explore.js');
// Sorted: the order islands register in is no part of the policy.
const hashes = [...(await styleHashes())].sort();
const script = `'sha256-${createHash('sha256').update(THEME_SCRIPT).digest('base64')}'`;
await writeFile(
  new URL('../src/hosting/csp-hashes.ts', import.meta.url),
  `// Generated by \`pnpm caddyfile\`. Don't edit by hand.
// The CSP allows these inline elements by hash, so neither style-src nor script-src needs
// 'unsafe-inline' (src/hosting/headers.ts).

/** Each island's declarative shadow root <style>. */
export const STYLE_HASHES: readonly string[] = [
${hashes.map((h) => `  ${JSON.stringify(h)},`).join('\n')}
];

/** The theme script in every page's <head> (src/domain/theme.ts). */
export const SCRIPT_HASHES: readonly string[] = [
  ${JSON.stringify(script)},
];
`,
);
// headers.ts reads the hashes, so it's imported after they're written.
const { caddyfile } = await import('../src/hosting/headers.js');
await writeFile(new URL('../Caddyfile', import.meta.url), caddyfile());
console.log(`wrote src/hosting/csp-hashes.ts (${String(hashes.length + 1)} hashes) and Caddyfile`);
